GEE_SERVICE_ACCOUNT = "gee-service@ee-shpp.iam.gserviceaccount.com"

GEE_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5M+rCHdPkdVM/
PXPnQAK0EzmY3veULfM2Ni/Is+O1Z0FT7BqqxO/BLl6pXFbj49bgSXfZtQs7pPCz
Ajz/Z78tHLfvi0Z/l3ehoS+/wt6guThOyQVIsCpDPFKhCAQpp8lmc59/UcTIh9EV
LI2t/12/pqdVwZ/mAcR2MjhRMZ2YRyZeWbgvpJkFNgkh15RUspiDe+VDZjL6eKWU
WL6J9jRKdA4nxHuF/5wPlrYlV5YSAaQitjgXjoIXKK7wU8eoe9MkN2iBNIEF6/Mf
bD4BUJt3B77p9T1LeAesG3ExxuGM7daY4rpzasT/IJfcLbNdxd71k3+PcVKL6tQP
8c3koni1AgMBAAECggEAUjKfq94PMGN+OiAtM+KuEHxD4Px8x7CJNHNiS+LDWrzk
Orocr9ROUOAitWo9SlHSCaOx5Nc8kBFJnzmMFxNVv1DytgeLl4+DUiI3DhYQNydd
vWHszXEaoNLCHaRwLIjCk40XqiuBejsFai9nBmXDlw8BT8drD2uTZZ4ubqLlvjJ8
pWWdV4RyvkG5lbR/klEcqYs+KOXJY3ddpygAf7qOOKC/GzYb/iiZHWGya86WY53n
ATDtX/FoHkU8eFdWUxC8QyuBvTOstIrQaVzPItlxro85hpHDnddjok3/h7gNwJUP
gzm7XFphkJwH/NG5KPwPLK1dRuU68fRnocLAsYlE9QKBgQDabxoKsLfQGFeO418t
zw+/IWcbCkmx2YJ2DpA1f2kympUxVZ+O1P4k/m3bhuVznidQ7SAryBB7lzq6wx+N
38CrlkHJR6KqXCXwnm3HQGxxlW/ffMEb/EqnGDNMjY1N1rYygbD0QFabvrCIv+NV
M4vzFcnnKfmpcTntNaLW/bbj1wKBgQDZDcKY/OXq6wRFbKG8uPDl8gjApWtOxCND
pXP6AbtGXGsD0/2XHXvg24AcUvnCUwEWug2ms7aZTmky9YnI8wvwC9qGIGCGvNvR
y+ziLwhv+UuwYJSHH/V3zEgYVwZMEsfxv+21ooxKCURElDoM9YFXcc2b6h+JJUIW
96XxSwr2UwKBgEzP4PJ9bkYJKVEf96peNAVcM6u4lG2sNUpamK+XXGDlJy2wFGnf
0Hcl2W/nIezkYqL8n+GFevZbGdXvI7t6QYCVWBD11efee6D/tU7qArh2el62uhmj
QIU951w2Msh6hpuAK7/YmBwwlFeiUsj1VXNn6BYYFqlVHa+iut6rXZMFAoGAQmd1
S3zDknVIHz021hf2i0La7qUtCTH0X/O0YZ45/zKzAr7ObHb2uTouHXw9MPhX8u4E
0yVUDd7xTEfWWYYR9uSJfFNXdKE+1xZ+aExfVnJ8d390sUpTvMzgmaG2KXvtc8Z2
IQWTyeq/2gNHJ0PMyEXm03ZzI3AkogYt3H5K4kUCgYBcAQSJT+X9S2zX9FSowTM9
z7Tk+3fQlKGgk6wqEvDeUl9MQp41piDJKEWp9m7K+L+eXO1txl9mWtqjtl2wlhIY
W8KBr4gC+QWp2VWAtviPhrSogeCiA6VMt4HWE8VnafmTZ/WZGcJfOm9YPCuNgaao
d+WMEhGuAuQIm+57jl7mmA==
-----END PRIVATE KEY-----"""
